//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp_HastaneOtomasyonu
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doktorlar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Doktorlar()
        {
            this.Randevus = new HashSet<Randevu>();
        }
    
        public int DoktorID { get; set; }
        public Nullable<int> PoliklinikID { get; set; }
        public int PersonelID { get; set; }
    
        public virtual Personel Personel { get; set; }
        public virtual Poliklinik Poliklinik { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Randevu> Randevus { get; set; }
    }
}
