//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp_HastaneOtomasyonu
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HastaneOtomasyonEntities2 : DbContext
    {
        public HastaneOtomasyonEntities2()
            : base("name=HastaneOtomasyonEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cinsiyet> Cinsiyets { get; set; }
        public virtual DbSet<Doktorlar> Doktorlars { get; set; }
        public virtual DbSet<Hasta> Hastas { get; set; }
        public virtual DbSet<HastaGecmisi> HastaGecmisis { get; set; }
        public virtual DbSet<HastaneBilgi> HastaneBilgis { get; set; }
        public virtual DbSet<Ilaclar> Ilaclars { get; set; }
        public virtual DbSet<Izinler> Izinlers { get; set; }
        public virtual DbSet<KanGrubu> KanGrubus { get; set; }
        public virtual DbSet<Meslek> Mesleks { get; set; }
        public virtual DbSet<Personel> Personels { get; set; }
        public virtual DbSet<Poliklinik> Polikliniks { get; set; }
        public virtual DbSet<Randevu> Randevus { get; set; }
        public virtual DbSet<ReceteDetay> ReceteDetays { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<RandevuDetay> RandevuDetays { get; set; }
    }
}
